# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, 30.10.2022

### Author: Eero Suomalainen

**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

In [ ]:
(a) Both being silent is better than both betraying each other so -x > -z.
    Betraying while other remains silent is the most beneficial scenario so -y > -w.
    Nash equilibrium occurs when on betrays and other remains silent. From this perspective -y > -x and -z > -w.
    This way -y > -x > -z > -w.

In [5]:
! pip install nashpy==0.0.21

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 6.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 7.0 MB/s eta 0:00:0000:0100:01
  Created wheel for nashpy: filename=nashpy-0.0.21-py3-none-any.whl size=15260 sha256=2c75a263865766c3fb8dfb4a89671508a688b2976c4382f84a5b036848bb802e
  Stored in directory: /home/jovyan/.cache/pip/wheels/02/08/62/cf4fa931e0a317d180936b266169a57f4bb4eb801465bbe8a1
Successfully built nashpy


In [2]:
import numpy as np
import nashpy as nash

In [3]:
# Test 1 (-y > -x > -z > -w) -> x=1, y=0, z=2 and w=3
A = [[-1, -3], [0, -2]]
B = [[-1, 0], [-3, -2]]
pd = nash.Game(A, B)
pd

Bi matrix game with payoff matrices:

Row player:
[[-1 -3]
 [ 0 -2]]

Column player:
[[-1  0]
 [-3 -2]]

In [4]:
eqs = pd.support_enumeration()
list(eqs)

[(array([0., 1.]), array([0., 1.]))]

In [ ]:
The output reads as follows: Both A and B cooperate with probability of 0 and both will betray with probability of 1.

In [5]:
# Test 2 (-w > -z) -> x=1, y=0, z=3 and w=2
A = [[-1, -2], [0, -3]]
B = [[-1, 0], [-2, -3]]
pd = nash.Game(A, B)
pd

Bi matrix game with payoff matrices:

Row player:
[[-1 -2]
 [ 0 -3]]

Column player:
[[-1  0]
 [-2 -3]]

In [6]:
eqs = pd.support_enumeration()
list(eqs)

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

In [ ]:
The output reads as follows: First line: A cooperates with probability of 1 and betrays with probability of 0
                                         while B cooperates with probability of 0
                                         and betrays with probability of 1.
        
                             Second line: A cooperates with probability of 0 and betrays with probability of 1
                                          while B cooperates with probability of 1
                                          and betrays with probability of 0.
                    
                             Third line: Both A and B cooperate with probability of 0.5
                                         and both will betray with probability of 0.5.

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**


**2. Competitive companies in the market discussing standardization.**


**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**


**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**

1. Yes. It's advantageous to batray other as you can get shortest sentance or second longest. If you cooperate you get    second shortest sentance or longest sentance.

2. No. The most beneficial for both is to cooperate since this way they can agree on one standard but if one of them      betrays the other there are now two (possibly conflicting) standards. Same is if both betray.

3. No as both work towards same goal and one really cannot get more energy efficient on cost of another.

4. Maybe yes. If both work with sahred resources then betraying another can net more profits for one. Both betraying each other can be costly but it might be less costly than cooperating while other betrays.